[versions]
curator = "5.6.0"
junit = "5.10.1"
testcontainers = "1.19.6"
awaitility = "4.2.0"
zookeeper = "3.9.1"

[libraries]
curator-recipes = { module = "org.apache.curator:curator-recipes", version.ref = "curator" }
curator-framework = { module = "org.apache.curator:curator-framework", version.ref = "curator" }
junit = { module = "org.junit:junit-bom", version.ref = "junit" }
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }
testcontainers = { module = "org.testcontainers:testcontainers-bom", version.ref = "testcontainers" }
zookeeper = { module = "org.apache.zookeeper:zookeeper", version.ref = "zookeeper" }

[bundles]
curator = ["curator-recipes", "curator-framework"]

[plugins]
springBoot = { id = "org.springframework.boot", version = "3.2.2" }
springDependencyManagement = { id = "io.spring.dependency-management", version = "1.1.4" }
axionRelease = { id = "pl.allegro.tech.build.axion-release", version = "1.16.1" }
nexusPublish = { id = "io.github.gradle-nexus.publish-plugin", version = "1.3.0" }
